package frc.team832.robot.auto;

public enum PrimaryAction {
	ROCKET_CLOSE,
	ROCKET_FAR,
	CARGO_FRONT_LEFT,
	CARGO_FRONT_RIGHT,
	CARGO_LEFTSIDE1,
	CARGO_LEFTSIDE2,
	CARGO_LEFTSIDE3,
	CARGO_RIGHTSIDE1,
	CARGO_RIGHTSIDE2,
	CARGO_RIGHTSIDE3,
}
